<?php
/**
 * Run this ONCE after importing skillmapping.sql, to create the default accounts
 * with real bcrypt password hashes generated by *your* PHP installation
 * (hashes are not portable to copy/paste from elsewhere, so we generate them here).
 *
 * Usage (command line, from the backend/database folder):
 *     php seed_users.php
 *
 * Or open it in the browser once:
 *     http://localhost/skillmapping/backend/database/seed_users.php
 *
 * It is safe to run multiple times — it skips accounts that already exist.
 */

require_once __DIR__ . '/../config/db.php';

$accounts = [
    ['username' => 'admin', 'password' => 'admin123', 'full_name' => 'ผู้ดูแลระบบ', 'role' => 'admin'],
    ['username' => 'user',  'password' => 'user123',  'full_name' => 'ผู้ใช้งานทั่วไป', 'role' => 'user'],
];

$db = getDB();
$check = $db->prepare('SELECT id FROM users WHERE username = ?');
$insert = $db->prepare('INSERT INTO users (username, password_hash, full_name, role) VALUES (?, ?, ?, ?)');

$created = [];
foreach ($accounts as $acc) {
    $check->execute([$acc['username']]);
    if ($check->fetch()) {
        $created[] = "{$acc['username']} (มีอยู่แล้ว — ข้าม)";
        continue;
    }
    $hash = password_hash($acc['password'], PASSWORD_BCRYPT);
    $insert->execute([$acc['username'], $hash, $acc['full_name'], $acc['role']]);
    $created[] = "{$acc['username']} / {$acc['password']}  (role: {$acc['role']}) — สร้างสำเร็จ";
}

$isCli = php_sapi_name() === 'cli';
$nl = $isCli ? "\n" : "<br>";
if (!$isCli) echo "<pre style='font-family:monospace'>";
echo "Seeding default accounts...$nl$nl";
foreach ($created as $line) echo "- $line$nl";
echo "{$nl}เสร็จสิ้น — สามารถลบไฟล์นี้ทิ้งได้หลังใช้งานแล้ว เพื่อความปลอดภัย$nl";
if (!$isCli) echo "</pre>";
